### ISSUE TITLE
packages for Debian/Ubuntu don't contain .so file

### ISSUE THREAD

**Issue by zandbelt** [OpenIDC/liboauth2#46]
for versions >= 1.4.5.3 <=1.5.1 the .deb files for liboauth2 for Debian/Ubuntu would not contain the .so symbolic link (anymore) but only the .so.0 files; that in its turn would result in dependent modules being linked statically against liboauth2 so updates of the library would not actually result in an upgrade of the functionality

**Comment by zandbelt** [comment]
updated packages with packaging version number "-2" in https://github.com/OpenIDC/liboauth2/releases/tag/v1.5.1 and various dependent modules

**Comment by chris-crunchr** [comment]
Thanks for fixing this! Caused some confusion for me, but I'm happy its all cleared up. I have one amendment concerning versioning: found that all versioned `.so` files have version `0.0.0` in the filename, instead of the actual version. This makes identifying the actual version a tiny bit harder. Other than that, all is fine.
